# Generated by Django 4.1.10 on 2023-07-22 14:29

# Django
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("face_images", "0001_initiate_face_images_models"),
    ]

    operations = [
        migrations.AlterField(
            model_name="faceimage",
            name="image_url",
            field=models.URLField(unique=True, verbose_name="Image URL"),
        ),
    ]
