version: "3.9"

services:
  face_embeddings_db:
    image: postgres:13
    restart: always
    environment:
      DATABASE_URL: ${DATABASE_URL}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 10s
      retries: 5
    volumes:
      - postgres_data:/var/lib/postgresql/data

  face_embeddings_app:
    image: face_embeddings
    container_name: face_embeddings
    env_file:
      - .env
    build:
      context: .
    environment:
      DATABASE_URL: ${DATABASE_URL}
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - logs_volume:/app/logs
      - static_volume:/app/static
      - media_volume:/app/media
    depends_on:
      - face_embeddings_db

volumes:
  postgres_data:
  logs_volume:
  static_volume:
  media_volume:
